import { roomCode } from '../utils/ids.js';
import { hashPassword, comparePassword } from '../utils/password.js';
import { store } from '../store/memoryStore.js';
import { GAME_CONFIG } from '../config/gameConfig.js';
import { makeGame } from '../services/gameService.js';
const cleanId=v=>String(v??'').replace(/\D/g,'').slice(0,6);
export async function createRoom(req,res){const count=Number(req.body?.maxPlayers);if(!Number.isInteger(count)||count<2||count>5)return res.status(400).json({message:'Choose between 2 and 5 players'});const user=store.users.get(String(req.auth.sub));if(!user)return res.status(401).json({message:'User not found. Please log in again.'});let roomId=roomCode();while(store.rooms.has(roomId))roomId=roomCode();const room={roomId,roomName:String(req.body?.roomName||'Friends Room').trim().slice(0,50)||'Friends Room',passwordHash:await hashPassword(String(req.body?.password||'')),hostId:String(user._id),maxPlayers:count,status:'WAITING',players:[{userId:String(user._id),uid:user.uid,username:user.username,ready:false}],gameId:null,rematchReady:new Set()};store.rooms.set(roomId,room);res.status(201).json({room:publicRoom(room)});}
export async function joinRoom(req,res){const roomId=cleanId(req.body?.roomId),password=String(req.body?.password??'');if(!/^\d{6}$/.test(roomId))return res.status(400).json({message:'Room ID must contain exactly 6 numbers'});const room=store.rooms.get(roomId);if(!room)return res.status(404).json({message:'Room not found'});if(room.status!=='WAITING')return res.status(409).json({message:'This game has already started'});const user=store.users.get(String(req.auth.sub));if(!user)return res.status(401).json({message:'User not found. Please log in again.'});if(room.players.some(p=>String(p.userId)===String(user._id)))return res.json({room:publicRoom(room),alreadyJoined:true});if(room.players.length>=room.maxPlayers)return res.status(409).json({message:'Room is full'});if(!await comparePassword(password,room.passwordHash))return res.status(401).json({message:'Incorrect room password'});room.players.push({userId:String(user._id),uid:user.uid,username:user.username,ready:false});res.json({room:publicRoom(room)});}
export function publicRoom(room){return {roomId:room.roomId,roomName:room.roomName,hostId:String(room.hostId),maxPlayers:room.maxPlayers,status:room.status,gameId:room.gameId||null,players:room.players.map(p=>({userId:String(p.userId),uid:p.uid,username:p.username,ready:Boolean(p.ready)}))};}
export function startRoom(room){if(room.players.length<2)throw new Error('At least 2 players are required');if(!room.players.every(p=>p.ready))throw new Error('Every player must be ready before the host starts the match');if(room.status!=='WAITING')throw new Error('Room cannot be started now');room.status='PLAYING';room.rematchReady=new Set();const game=makeGame(room);store.games.set(game.gameId,game);room.gameId=game.gameId;return game;}
