import mongoose from 'mongoose';
import User from '../models/User.js';
import { verifyToken } from '../utils/auth.js';import { store } from '../store/memoryStore.js';import { publicRoom,startRoom } from '../controllers/roomController.js';import { submitBoard,callNumber,makeGame } from '../services/gameService.js';import { id } from '../utils/ids.js';
const norm=v=>String(v||'').replace(/\D/g,'').slice(0,6);const userSockets=id=>[...(store.onlineSockets.get(String(id))||[])];
function onlineList(except){return [...store.users.values()].filter(u=>String(u._id)!==String(except)&&store.onlineSockets.has(String(u._id))).map(u=>({userId:String(u._id),uid:u.uid,username:u.username,online:true}));}
function emitPresence(io){for(const s of io.sockets.sockets.values())s.emit('presence:list',{players:onlineList(s.user?.sub)});}
function emitRoom(io,room){io.to(room.roomId).emit('room:update',{room:publicRoom(room)});}
function publicGame(game,userId){return {...game,players:game.players.map(p=>({...p,board:String(p.userId)===String(userId)?p.board:[]}))};}
async function persistScores(game){const finished=game.status==='FINISHED';for(const p of game.players){const u=store.users.get(String(p.userId));if(u){u.totalScore=(u.totalScore||0)+(p.points||0);u.totalGames=(u.totalGames||0)+1;if(p.rank===1)u.wins=(u.wins||0)+1;else if(finished)u.losses=(u.losses||0)+1;}if(mongoose.connection.readyState===1){await User.findByIdAndUpdate(p.userId,{$inc:{totalScore:p.points||0,totalGames:1,wins:p.rank===1?1:0,losses:finished&&p.rank!==1?1:0}}).catch(()=>{});}}}
function broadcastGame(io,game,event='game:state',extra={}){for(const sid of io.sockets.adapter.rooms.get(game.roomId)||[]){const s=io.sockets.sockets.get(sid);if(s)s.emit(event,{game:publicGame(game,s.user.sub),...extra});}}
export function configureSockets(io){io.use((s,n)=>{try{const t=s.handshake.auth?.token;if(!t)return n(new Error('Authentication required'));s.user=verifyToken(t);n();}catch{return n(new Error('Invalid socket authentication'));}});io.on('connection',socket=>{const me=String(socket.user.sub);if(!store.onlineSockets.has(me))store.onlineSockets.set(me,new Set());store.onlineSockets.get(me).add(socket.id);emitPresence(io);
 socket.on('room:join',({roomId},ack)=>{const room=store.rooms.get(norm(roomId));if(!room)return ack?.({ok:false,message:'Room not found'});if(!room.players.some(p=>String(p.userId)===me))return ack?.({ok:false,message:'You are not a room member'});socket.join(room.roomId);emitRoom(io,room);ack?.({ok:true,room:publicRoom(room)});});
 socket.on('room:leave',({roomId})=>{const room=store.rooms.get(norm(roomId));if(!room)return;const wasHost=String(room.hostId)===me;room.players=room.players.filter(p=>String(p.userId)!==me);if(!room.players.length){store.rooms.delete(room.roomId);socket.leave(room.roomId);return;}if(wasHost){const onlineMember=room.players.find(p=>store.onlineSockets.has(String(p.userId)));room.hostId=String((onlineMember||room.players[0]).userId);}room.status='WAITING';room.gameId=null;room.players.forEach(p=>p.ready=false);emitRoom(io,room);socket.leave(room.roomId);});
 socket.on('room:ready',({roomId,ready})=>{const room=store.rooms.get(norm(roomId));const p=room?.players.find(x=>String(x.userId)===me);if(!p)return;p.ready=!!ready;emitRoom(io,room);});
 socket.on('room:start',({roomId})=>{try{const room=store.rooms.get(norm(roomId));if(!room)throw Error('Room not found');if(String(room.hostId)!==me)throw Error('Only the host can start the match');const game=startRoom(room);io.to(room.roomId).emit('room:started',{room:publicRoom(room),game:{...game,players:game.players.map(p=>({...p,board:[]}))}});}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('room:invite',({roomId,targetUserId})=>{try{const room=store.rooms.get(norm(roomId)),targetId=String(targetUserId);if(!room)throw Error('Room not found');if(!room.players.some(p=>String(p.userId)===me))throw Error('Join the room before inviting');if(room.status!=='WAITING'||room.players.length>=room.maxPlayers)throw Error('Room is unavailable');if(!store.onlineSockets.has(targetId))throw Error('Player is offline');if(room.players.some(p=>String(p.userId)===targetId))throw Error('Player is already in this room');const existing=[...store.roomInvites.values()].find(v=>v.roomId===room.roomId&&v.fromUserId===me&&v.toUserId===targetId&&Date.now()<v.cooldownUntil);if(existing)throw Error(`You can invite this player again in ${Math.ceil((existing.cooldownUntil-Date.now())/1000)} seconds`);const inviteId=id();store.roomInvites.set(inviteId,{inviteId,roomId:room.roomId,fromUserId:me,toUserId:targetId,expiresAt:Date.now()+120000,cooldownUntil:Date.now()+30000});const from=store.users.get(me);for(const sid of userSockets(targetId))io.to(sid).emit('room:invite',{inviteId,roomId:room.roomId,roomName:room.roomName,inviter:{userId:me,username:from?.username}});socket.emit('room:invite:response',{inviteId,targetUserId:targetId,accepted:null,message:'Invite sent'});}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('room:invite:accept',({inviteId})=>{try{const inv=store.roomInvites.get(String(inviteId));if(!inv||inv.toUserId!==me)throw Error('Invite is no longer valid');const room=store.rooms.get(inv.roomId);if(!room||Date.now()>inv.expiresAt||room.status!=='WAITING'||room.players.length>=room.maxPlayers)throw Error('Room is no longer available');const u=store.users.get(me);if(!room.players.some(p=>String(p.userId)===me))room.players.push({userId:me,uid:u.uid,username:u.username,ready:false});store.roomInvites.delete(inviteId);socket.join(room.roomId);emitRoom(io,room);socket.emit('room:joined',{inviteId,room:publicRoom(room)});for(const sid of userSockets(inv.fromUserId))io.to(sid).emit('room:invite:response',{inviteId,targetUserId:me,accepted:true,message:`${u.username} accepted your invite`});}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('room:invite:reject',({inviteId})=>{const inv=store.roomInvites.get(String(inviteId));if(!inv||inv.toUserId!==me)return;store.roomInvites.delete(String(inviteId));const u=store.users.get(me);for(const sid of userSockets(inv.fromUserId))io.to(sid).emit('room:invite:response',{inviteId,targetUserId:me,accepted:false,message:`${u?.username||'Player'} rejected your invite`});});
 socket.on('room:rematch',({roomId})=>{try{const room=store.rooms.get(norm(roomId));if(!room)throw Error('Room not found');if(!room.players.some(p=>String(p.userId)===me))throw Error('You are not a room member');if(room.status!=='FINISHED')throw Error('Rematch is available after the match finishes');room.status='PLAYING';room.players.forEach(p=>p.ready=false);const game=makeGame(room);store.games.set(game.gameId,game);room.gameId=game.gameId;io.to(room.roomId).emit('room:started',{room:publicRoom(room),game:{...game,players:game.players.map(p=>({...p,board:[]}))}});}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('game:join',({gameId})=>{const g=store.games.get(gameId);if(!g||!g.players.some(p=>String(p.userId)===me))return;socket.join(g.roomId);socket.emit('game:state',{game:publicGame(g,me)});});
 socket.on('game:boardSubmit',({gameId,board})=>{try{const g=store.games.get(gameId);if(!g)throw Error('Game not found');submitBoard(g,me,board);broadcastGame(io,g);}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('game:numberCall',async({gameId,number})=>{try{const g=store.games.get(gameId);if(!g)throw Error('Game not found');const r=callNumber(g,me,Number(number));if(g.status==='FINISHED'){const room=store.rooms.get(g.roomId);if(room)room.status='FINISHED';await persistScores(g);}broadcastGame(io,g,'game:move',{actor:r.actor,number:r.number,resultEvent:r.resultEvent});}catch(e){socket.emit('error:message',{message:e.message});}});
 socket.on('disconnect',()=>{const set=store.onlineSockets.get(me);if(set){set.delete(socket.id);if(!set.size)store.onlineSockets.delete(me);}for(const room of store.rooms.values()){if(String(room.hostId)!==me)continue;const stillOnline=store.onlineSockets.has(me);if(stillOnline)continue;const members=room.players.filter(p=>String(p.userId)!==me);if(!members.length){store.rooms.delete(room.roomId);continue;}const nextHost=members.find(p=>store.onlineSockets.has(String(p.userId)))||members[0];room.hostId=String(nextHost.userId);if(room.status==='WAITING'){room.players.forEach(p=>{if(String(p.userId)!==me)p.ready=false;});}emitRoom(io,room);}emitPresence(io);});});}
